<?php
define("MYSQL_USERNAME", "YOUR_USERNAME (DEFAULT = ROOT)");
define("MYSQL_PASSWORD", "YOUR_PASSWORD (DEFAULT = NULL)");
define("MYSQL_HOSTNAME", "YOUR_HOSTNAME (LOCALHOST)");
define("MYSQL_DATABASE", "YOUR_DATABASE-NAME");